### PR TITLE
ignore non image files

### LINKED ISSUE #267: [Bug] Considers .nomedia files as images
---

## Device information

- Tachidesk version: v0.5.4-r1045-windows-x64
- Server Operating System: Windows 10 19043.1319
- Server Desktop Environment: N/A
- Server JVM version: OpenJDK 8.0.302+8
- Client Operating System: Same as the server
- Client Web Browser: Google Chrome 96 and Firefox 95

## Steps to reproduce
1. Have  .nomedia file in a chapter folder
2. The server send the .nomedia as the first image

### Expected behavior
complete ignore the nomedia file when sending the images and when counting the pages

### Actual behavior
Serves the .nomedia file as the First image and also counts it as a page

## Other details
This might only happen when someone copies a download folder from Tachiyomi on android to the Tachidesk manga/local folder as Tachidesk it self does not use any.nomedia file

### PR DESCRIPTION
**Pull request by AriaMoradi**
closes #267

### CODE REVIEW

File: server/src/main/kotlin/eu/kanade/tachiyomi/source/local/LocalSource.kt [hunk 1]
```diff
@@ -293,12 +293,15 @@ class LocalSource : CatalogueSource {
...
                 Observable.just(
-                    chapterFile.listFiles().orEmpty().sortedBy { it.name }.mapIndexed { index, page ->
-                        Page(
-                            index,
-                            imageUrl = applicationDirs.localMangaRoot + "/" + chapter.url + "/" + page.name
-                        )
-                    }
+                    chapterFile.listFiles().orEmpty()
+                        .sortedBy { it.name }
+                        .filter { !it.isDirectory && ImageUtil.isImage(it.name) { FileInputStream(it) } }
```
Comment (Syer10) [inline server/src/main/kotlin/eu/kanade/tachiyomi/source/local/LocalSource.kt]:
```suggestion
                        .filter { !it.isDirectory && ImageUtil.isImage(it.name, it::inputStream)
```

**Review by Syer10 — COMMENTED** [review]
I would suggest using this instead, otherwise looks fine
