### PR TITLE
snowmtl extension error fix: dynamic retrieval

### LINKED ISSUE #1370: Manga is not displaying in certain extensions
### Steps to reproduce

Go to the Browse section and install Snow Machine or Solar Machine extensions and pick a random manga to read. After selecting a manga, select a random chapter to read and the error shown below just appears and no images are displayed

Image

### Expected behavior

The expected behavior is that when i click on a chapter, the images for that chapter are supposed to load and appear

### Actual behavior

The manga reader section that loads the chapter images is not displaying any images for the Snow Machine Translations extensions and the Solar Machine Translation extensions the image below shows the error it's returning

Image

Also with manga with shorter titles, it just shows retry, as seen in the image below

Image

### Suwayomi-Server version

v2.0.1727

### Server operating system

MacOS

### Server Desktop Environment

_No response_

### Server JVM version

openjdk 21.0.6

### Used client name

Suwayomi-WebUI

### Client version

r2467

### Used web browser

Safari

### Client operating system

MacOS

### Other details

All the other extensions are working

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title (ideally less than ~100 characters).
- [x] I have tried the troubleshooting guide described in [README.md](https://github.com/Suwayomi/Suwayomi-Server?tab=readme-ov-file#troubleshooting-and-support)
- [x] I have updated to the **[latest version](https://github.com/suwayomi/suwayomi-server/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Suwayomi does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

### LINKED ISSUE #1472: SnowMTL:This problem is happening in Suwayomi but not in Komikku
### Steps to reproduce

this problem is happening in some chapters of snowmtl extensions.

### Expected behavior

the chapter should show

### Actual behavior

Image

Image

### Suwayomi-Server version

v2.0.1809

### Server operating system

windows 11 24h2

### Server Desktop Environment

_No response_

### Server JVM version

java version "24.0.1" 2025-04-15

### Used client name

webui

### Client version

windows 11 24h2

### Used web browser

firefox 139.0.4

### Client operating system

windows 11 24h2

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title (ideally less than ~100 characters).
- [x] I have tried the troubleshooting guide described in [README.md](https://github.com/Suwayomi/Suwayomi-Server?tab=readme-ov-file#troubleshooting-and-support)
- [x] I have updated to the **[latest version](https://github.com/suwayomi/suwayomi-server/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Suwayomi does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

### PR DESCRIPTION
**Pull request by Chiru-Dey**
image
tried to solve this through dynamic retrieval images.

### CODE REVIEW

File: server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt [hunk 1]
```diff
@@ -91,15 +91,12 @@ object Page {
             )
         progressFlow?.invoke(tachiyomiPage.progress)
 
-        // we treat Local source differently
```
Comment (Syer10) [inline server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt]: Revert removed comments

**Review by Syer10 — CHANGES_REQUESTED** [review]
I'm fine with this workaround, I will test it when I am able to  and verify it works before merging it, just revert the removed comments.

File: server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt (hunk 1 above)
Comment (Chiru-Dey) [reply server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt]: you want all the comments? or that specific one?

**Comment by Chiru-Dey** [comment]
what about the pull request. i didnot see any kotlin linting errors in vscode. shall i try to run your specifice command?

File: server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt (hunk 1 above)
Comment (Syer10) [reply server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Page.kt]: Yes, there was no reason to remove them.

**Comment by Syer10** [comment]
Run `./gradlew ktlintformat`

**Review by Syer10 — APPROVED** [review]
Seems to work

**Comment by Chiru-Dey** [comment]
Ok.  now what I have to do?

**Comment by maxpiva** [comment]
@Syer10  @Chiru-Dey  I don't think this is working, folks. Since `getImageUrl` is not overridden by SnowMTL, it falls back to the base `HttpSource` implementation, which results in incorrect behavior. Only `pageListParse` correctly generates the image URLs.

Effectively, you're asking `HttpSource` to retrieve an image using a null `imageUrl`.

On a related note, I'm running some POCs on the extensions by Gzipping the metadata. However, after extended testing, I've found that some cases still exceed the 2048-character limit, even after compression. Does the database support unicode or utf-16?, so maybe I can encode in Base2048 instead base64?

```
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
 [DefaultDispatcher-worker-11] suwayomi.tachidesk.server.JavalinSetup -- IllegalArgumentException while handling the request
 java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1360)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1734)
        at okhttp3.Request$Builder.url(Request.kt:233)
        at eu.kanade.tachiyomi.network.RequestsKt.GET(Requests.kt:24)
        at eu.kanade.tachiyomi.network.RequestsKt.GET$default(Requests.kt:17)
        at eu.kanade.tachiyomi.source.online.HttpSource.imageUrlRequest(HttpSource.kt:355)
        at eu.kanade.tachiyomi.source.online.HttpSource.fetchImageUrl(HttpSource.kt:345)
        at eu.kanade.tachiyomi.source.online.HttpSource.getImageUrl$suspendImpl(HttpSource.kt:340)
        at eu.kanade.tachiyomi.source.online.HttpSource.getImageUrl(HttpSource.kt)
        at suwayomi.tachidesk.manga.impl.Page.getTrueImageUrl(Page.kt:44)
        at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:114)
        at suwayomi.tachidesk.manga.controller.MangaController$pageRetrieve$2$1$1.invokeSuspend(MangaController.kt:417)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
```

**Comment by Syer10** [comment]
Dang. At this point its probably not worth trying a more complicated fix. We should just remove the varchar character limit for that column in the database

**Comment by schroda** [comment]
@maxpiva you sure that's the same error? It works fine for me.

The `HttpSource#getImageUrl` is also fetching the `imageUrl` via the page `url` (which are two different urls), so it being null doesn't matter.

**Comment by maxpiva** [comment]
You're right,  it is using `url`, but in the case of `SnowMTL`, the `url` is either null or empty, and the method isn't overridden. As a result, HttpSource ends up trying to retrieve a null URL.


image

Don't pay attention to the extra URL metadata, I'm using a forked version of SnowMTL that compresses the JSON and encodes it in Base64.

image

**Comment by schroda** [comment]
~I see, something like this would work https://github.com/Suwayomi/Suwayomi-Server/compare/master...schroda:Tachidesk-Server:fix/handling_of_too_long_page_image_urls~

**Comment by Chiru-Dey** [comment]
i created a new pr request that fixes the page load error- https://github.com/Suwayomi/Suwayomi-Server/pull/1542
