### PR TITLE
Remove "default" category from backups

### LINKED ISSUE #1207: [Bug] backup creating an extra default category
## Device information
- Suwayomi-Server version: v1.1.1-r1650
- Server Operating System: Windows11
- Server Desktop Environment: N/A
- Server JVM version: Java 21
- Client Operating System: Windows 11
- Client Web Browser: Opera

## Steps to reproduce
1. create backup
2. restore it in mihon or any fork

### Expected behavior
it shouldn't create an extra default category

### Actual behavior
it creates an extra default category

### PR DESCRIPTION
**Pull request by schroda**
Restoring a suwayomi backup in mihon created a category named "Default"

fixes #1207

### CODE REVIEW

File: server/src/main/kotlin/suwayomi/tachidesk/manga/impl/backup/proto/ProtoBackupExport.kt [hunk 1]
```diff
@@ -292,7 +293,8 @@ object ProtoBackupExport : ProtoBackupBase() {
             .orderBy(CategoryTable.order to SortOrder.ASC)
             .map {
                 CategoryTable.toDataClass(it)
-            }.map {
+            }.filter { it.id != Category.DEFAULT_CATEGORY_ID }
```
Comment (Syer10) [inline server/src/main/kotlin/suwayomi/tachidesk/manga/impl/backup/proto/ProtoBackupExport.kt:296]:
```suggestion
            }
            .filter { it.id != Category.DEFAULT_CATEGORY_ID }
```

Comment (schroda) [reply server/src/main/kotlin/suwayomi/tachidesk/manga/impl/backup/proto/ProtoBackupExport.kt:296]: that is getting auto formatted by the linter

**Review by Syer10 — APPROVED** [review]
